/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProcessingStatusService } from "../processingStatus.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProcessingStatusCreateInput } from "./ProcessingStatusCreateInput";
import { ProcessingStatus } from "./ProcessingStatus";
import { ProcessingStatusFindManyArgs } from "./ProcessingStatusFindManyArgs";
import { ProcessingStatusWhereUniqueInput } from "./ProcessingStatusWhereUniqueInput";
import { ProcessingStatusUpdateInput } from "./ProcessingStatusUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProcessingStatusControllerBase {
  constructor(
    protected readonly service: ProcessingStatusService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProcessingStatus })
  @nestAccessControl.UseRoles({
    resource: "ProcessingStatus",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProcessingStatus(
    @common.Body() data: ProcessingStatusCreateInput
  ): Promise<ProcessingStatus> {
    return await this.service.createProcessingStatus({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,
        message: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProcessingStatus] })
  @ApiNestedQuery(ProcessingStatusFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProcessingStatus",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async processingStatuses(
    @common.Req() request: Request
  ): Promise<ProcessingStatus[]> {
    const args = plainToClass(ProcessingStatusFindManyArgs, request.query);
    return this.service.processingStatuses({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,
        message: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProcessingStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProcessingStatus",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async processingStatus(
    @common.Param() params: ProcessingStatusWhereUniqueInput
  ): Promise<ProcessingStatus | null> {
    const result = await this.service.processingStatus({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,
        message: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProcessingStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProcessingStatus",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProcessingStatus(
    @common.Param() params: ProcessingStatusWhereUniqueInput,
    @common.Body() data: ProcessingStatusUpdateInput
  ): Promise<ProcessingStatus | null> {
    try {
      return await this.service.updateProcessingStatus({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          status: true,
          message: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProcessingStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProcessingStatus",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProcessingStatus(
    @common.Param() params: ProcessingStatusWhereUniqueInput
  ): Promise<ProcessingStatus | null> {
    try {
      return await this.service.deleteProcessingStatus({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          status: true,
          message: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
