/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SettingsService } from "../settings.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SettingsCreateInput } from "./SettingsCreateInput";
import { Settings } from "./Settings";
import { SettingsFindManyArgs } from "./SettingsFindManyArgs";
import { SettingsWhereUniqueInput } from "./SettingsWhereUniqueInput";
import { SettingsUpdateInput } from "./SettingsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SettingsControllerBase {
  constructor(
    protected readonly service: SettingsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Settings })
  @nestAccessControl.UseRoles({
    resource: "Settings",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSettings(
    @common.Body() data: SettingsCreateInput
  ): Promise<Settings> {
    return await this.service.createSettings({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        settingName: true,
        settingValue: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Settings] })
  @ApiNestedQuery(SettingsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Settings",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async settingsItems(@common.Req() request: Request): Promise<Settings[]> {
    const args = plainToClass(SettingsFindManyArgs, request.query);
    return this.service.settingsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        settingName: true,
        settingValue: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Settings })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Settings",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async settings(
    @common.Param() params: SettingsWhereUniqueInput
  ): Promise<Settings | null> {
    const result = await this.service.settings({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        settingName: true,
        settingValue: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Settings })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Settings",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSettings(
    @common.Param() params: SettingsWhereUniqueInput,
    @common.Body() data: SettingsUpdateInput
  ): Promise<Settings | null> {
    try {
      return await this.service.updateSettings({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          settingName: true,
          settingValue: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Settings })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Settings",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSettings(
    @common.Param() params: SettingsWhereUniqueInput
  ): Promise<Settings | null> {
    try {
      return await this.service.deleteSettings({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          settingName: true,
          settingValue: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
